# Generated by Django 4.0.2 on 2022-03-01 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(help_text='Type your mobile no', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^((\\+){1}91){1}[1-9]{1}[0-9]{9}$')])),
                ('secondary_mobile', models.CharField(help_text='Type your phone no', max_length=13, validators=[django.core.validators.RegexValidator('^((\\+){1}91){1}[1-9]{1}[0-9]{9}$')])),
                ('email', models.EmailField(max_length=254, verbose_name='Type your email address')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
