# Generated by Django 4.0.2 on 2022-03-01 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('NA', 'Rather not say'), ('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(help_text='Mobile NO: +9185XXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^((\\+){1}91){1}[1-9]{1}[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_mobile',
            field=models.CharField(help_text='Mobile NO: +9185XXXXXXXX', max_length=13, validators=[django.core.validators.RegexValidator('^((\\+){1}91){1}[1-9]{1}[0-9]{9}$')]),
        ),
    ]
