# Generated by Django 4.0.2 on 2022-03-01 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_gender_alter_contact_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('W', 'Work'), ('O', 'Other')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('U', 'Unmarried'), ('D', 'Divorced')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Type your email address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_mobile',
            field=models.CharField(help_text='Mobile NO: +9185XXXXXXXX', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^((\\+){1}91){1}[1-9]{1}[0-9]{9}$')]),
        ),
    ]
