# Generated by Django 4.0.2 on 2022-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('MyMarket', 'MyMarket')], max_length=30, null=True),
        ),
    ]
